t3

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -91,72 +91,73 @@ runs:
         PROJECT: ${{ inputs.project }}
         ENDPOINT: ${{ inputs.endpoint }}
       with:
-        entrypoint: /bin/sh
+        entrypoint: sh
         args: >-
-          -c '
-          if [ ! -z "${{ inputs.functions }}" ]; then
-            echo "${{ inputs.functions }}" | jq -c ".[]" | while read -r fn; do
-              type=$(echo $fn | jq -r ".type")
-              path=$(echo $fn | jq -r ".path")
-              desc=$(echo $fn | jq -r ".description")
-              uuid=$(echo $fn | jq -r ".uuid")
+          -c "
+          if [ ! -z '${{ inputs.functions }}' ]; then
+            echo '${{ inputs.functions }}' | jq -c '.[]' | while read -r fn; do
+              type=$(echo \"$fn\" | jq -r '.type');
+              path=$(echo \"$fn\" | jq -r '.path');
+              desc=$(echo \"$fn\" | jq -r '.description');
+              uuid=$(echo \"$fn\" | jq -r '.uuid');
 
-              if [ ! -f "$path" ]; then
-                echo "Error: Function file not found: $path"
-                exit 1
-              fi
+              if [ ! -f \"$path\" ]; then
+                echo 'Error: Function file not found: '$path;
+                exit 1;
+              fi;
 
-              case $type in
-                "auth")
-                  quant auth "$path" "$desc" "$uuid" -c $CUSTOMER -t $TOKEN -p $PROJECT -e $ENDPOINT
+              case \"$type\" in
+                'auth')
+                  quant auth \"$path\" \"$desc\" \"$uuid\" -c \"$CUSTOMER\" -t \"$TOKEN\" -p \"$PROJECT\" -e \"$ENDPOINT\";
                   ;;
-                "filter")
-                  quant filter "$path" "$desc" "$uuid" -c $CUSTOMER -t $TOKEN -p $PROJECT -e $ENDPOINT
+                'filter')
+                  quant filter \"$path\" \"$desc\" \"$uuid\" -c \"$CUSTOMER\" -t \"$TOKEN\" -p \"$PROJECT\" -e \"$ENDPOINT\";
                   ;;
-                "edge")
-                  quant function "$path" "$desc" "$uuid" -c $CUSTOMER -t $TOKEN -p $PROJECT -e $ENDPOINT
+                'edge')
+                  quant function \"$path\" \"$desc\" \"$uuid\" -c \"$CUSTOMER\" -t \"$TOKEN\" -p \"$PROJECT\" -e \"$ENDPOINT\";
                   ;;
                 *)
-                  echo "Error: Invalid function type: $type"
-                  exit 1
+                  echo 'Error: Invalid function type: '$type;
+                  exit 1;
                   ;;
-              esac
-            done
+              esac;
+            done;
+          fi;
+
+          if [ ! -z '${{ inputs.functions-file }}' ]; then
+            if [ ! -f '${{ inputs.functions-file }}' ]; then
+              echo 'Error: Functions file not found: ${{ inputs.functions-file }}';
+              exit 1;
+            fi;
+            cat '${{ inputs.functions-file }}' | jq -c '.[]' | while read -r fn; do
+              type=$(echo \"$fn\" | jq -r '.type');
+              path=$(echo \"$fn\" | jq -r '.path');
+              desc=$(echo \"$fn\" | jq -r '.description');
+              uuid=$(echo \"$fn\" | jq -r '.uuid');
+
+              if [ ! -f \"$path\" ]; then
+                echo 'Error: Function file not found: '$path;
+                exit 1;
+              fi;
+
+              case \"$type\" in
+                'auth')
+                  quant auth \"$path\" \"$desc\" \"$uuid\" -c \"$CUSTOMER\" -t \"$TOKEN\" -p \"$PROJECT\" -e \"$ENDPOINT\";
+                  ;;
+                'filter')
+                  quant filter \"$path\" \"$desc\" \"$uuid\" -c \"$CUSTOMER\" -t \"$TOKEN\" -p \"$PROJECT\" -e \"$ENDPOINT\";
+                  ;;
+                'edge')
+                  quant function \"$path\" \"$desc\" \"$uuid\" -c \"$CUSTOMER\" -t \"$TOKEN\" -p \"$PROJECT\" -e \"$ENDPOINT\";
+                  ;;
+                *)
+                  echo 'Error: Invalid function type: '$type;
+                  exit 1;
+                  ;;
+              esac;
+            done;
           fi
-
-          if [ ! -z "${{ inputs.functions-file }}" ]; then
-            if [ ! -f "${{ inputs.functions-file }}" ]; then
-              echo "Error: Functions file not found: ${{ inputs.functions-file }}"
-              exit 1
-            fi
-            cat "${{ inputs.functions-file }}" | jq -c ".[]" | while read -r fn; do
-              type=$(echo $fn | jq -r ".type")
-              path=$(echo $fn | jq -r ".path")
-              desc=$(echo $fn | jq -r ".description")
-              uuid=$(echo $fn | jq -r ".uuid")
-
-              if [ ! -f "$path" ]; then
-                echo "Error: Function file not found: $path"
-                exit 1
-              fi
-
-              case $type in
-                "auth")
-                  quant auth "$path" "$desc" "$uuid" -c $CUSTOMER -t $TOKEN -p $PROJECT -e $ENDPOINT
-                  ;;
-                "filter")
-                  quant filter "$path" "$desc" "$uuid" -c $CUSTOMER -t $TOKEN -p $PROJECT -e $ENDPOINT
-                  ;;
-                "edge")
-                  quant function "$path" "$desc" "$uuid" -c $CUSTOMER -t $TOKEN -p $PROJECT -e $ENDPOINT
-                  ;;
-                *)
-                  echo "Error: Invalid function type: $type"
-                  exit 1
-                  ;;
-              esac
-            done
-          fi'
+          "
     - name: Deploy Assets
       uses: "docker://quantcdn/cli:5.0.3"
       with:
